<?php

/**
 * @file
 * Contains product_builder_preview.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function product_builder_preview_theme() {
  return [
    'product_builder_preview_element' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_product_builder_preview_element(&$variables) {
  $element = $variables['element'];

  $suggestions = product_builder_preview_suggestions_list();
  $template_file = product_builder_preview_get_suggestion_template($suggestions);
  $template_variables = product_builder_preview_get_template_variables($template_file);

  foreach ($template_variables as $variable_name) {
    $variables[$variable_name] = $element["#$variable_name"];
  }
}

/**
 * Implements hook_form_alter().
 */
function product_builder_preview_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $form_builder = $form_state->getBuildInfo();
  if (isset($form_builder['base_form_id']) && ($form_builder['base_form_id'] == 'product_builder_form')) {
    $form['#pre_render'][] = 'product_builder_preview_product_builder_form_pre_render';
  }
}

/**
 * Pre render callback for product builder entity form.
 */
function product_builder_preview_product_builder_form_pre_render($elements) {

  $suggestions = product_builder_preview_suggestions_list();
  $template_file = product_builder_preview_get_suggestion_template($suggestions);
  $template_variables = product_builder_preview_get_template_variables($template_file);

  foreach ($template_variables as $variable_name) {
    if (isset($default_variables[$variable_name])) {
      continue;
    }

    if (!isset($elements['product_builder_preview_element'])) {
      $elements['product_builder_preview_element'] = [
        '#theme' => 'product_builder_preview_element',
        '#weight' => 100,
      ];
    }

    $elements['product_builder_preview_element']["#$variable_name"] = $elements[$variable_name];
    unset($elements[$variable_name]);
  }

  return $elements;
}

/**
 * Return product builder preview suggestions list.
 */
function product_builder_preview_suggestions_list() {
  return [
    'product_builder_preview_element',
  ];
}

/**
 * Get templates variables for template.
 */
function product_builder_preview_get_template_variables($template_file) {

  $variables = &drupal_static(__FUNCTION__, []);

  if (isset($variables[$template_file])) {
    return $variables[$template_file];
  }

  $twig_service = \Drupal::service('twig');
  $loader = \Drupal::service('twig.loader.filesystem');
  $parsed = $twig_service->parse($twig_service->tokenize($loader->getSource($template_file)));
  $variables[$template_file] = product_builder_preview_get_twig_variable_names($parsed);

  return $variables[$template_file];
}

/**
 * Get template for suggestions list.
 */
function product_builder_preview_get_suggestion_template($suggestions) {
  $theme_registry = \Drupal::service('theme.registry');
  $theme_registry = $theme_registry->getRuntime();
  foreach (array_reverse($suggestions) as $suggestion) {
    if ($theme_registry->has($suggestion)) {
      $info = $theme_registry->get($suggestion);
      break;
    }
  }

  $extension = '.html.twig';
  $template_file = $info['template'] . $extension;
  if (isset($info['path'])) {
    $template_file = $info['path'] . '/' . $template_file;
  }

  return $template_file;
}

/**
 * Get twig template variables names.
 */
function product_builder_preview_get_twig_variable_names($nodes) {
  $variables = [];
  foreach ($nodes as $node) {
    if ($node instanceof \Twig_Node_Expression_Name) {
      $name = $node->getAttribute('name');
      $variables[$name] = $name;
    } elseif ($node instanceof \Twig_Node_Expression_Constant && $nodes instanceof \Twig_Node_Expression_GetAttr) {
      $value = $node->getAttribute('value');
      if (!empty($value) && is_string($value)) {
        $variables[$value] = $value;
      }
    } elseif ($node instanceof \Twig_Node_Expression_GetAttr) {
      $path = implode('.', product_builder_preview_get_twig_variable_names($node));
      if (!empty($path)) {
        $variables[$path] = $path;
      }
    } elseif ($node instanceof \Twig_Node) {
      $variables += product_builder_preview_get_twig_variable_names($node);
    }
  }

  return $variables;
}
