services:
  product_builder.add_to_cart_lazy_builders:
    class: Drupal\product_builder\AddToCartProductBuilderLazyBuilders
    arguments: ['@entity_type.manager', '@form_builder', '@entity.repository']
