services:
  product_builder.add_to_cart_lazy_builders:
    class: Drupal\product_builder\AddToCartProductBuilderLazyBuilders
    arguments: ['@entity_type.manager', '@form_builder', '@entity.repository']

  product_builder.embed_product_builder_lazy_builders:
    class: Drupal\product_builder\EmbedProductBuilderLazyBuilders
    arguments: ['@entity_type.manager', '@form_builder', '@entity.repository']

  product_builder.route_subscriber:
    class: Drupal\product_builder\Routing\RouteSubscriber
    tags:
      - { name: event_subscriber }

  product_builder.add_to_cart_subscriber:
    class: Drupal\product_builder\EventSubscriber\ProductBuilderAddToCartEventSubscriber
    tags:
      - { name: event_subscriber }
