services:
  product_builder.product_builder_lazy_builders:
    class: Drupal\product_builder\ProductBuilderLazyBuilders
    arguments: ['@entity_type.manager', '@form_builder', '@entity.repository']

  product_builder.route_subscriber:
    class: Drupal\product_builder\Routing\RouteSubscriber
    tags:
      - { name: event_subscriber }
